### PR TITLE
Adding Support For Docker / Docker Compose

### PR DESCRIPTION
**Pull request by christopherhein**
> I'm not sure if this is something you would like to bring into the core, I've been working on the side to make `pushd` run in a docker container this pr adds support for such a thing. Feel free to comment or close, but since I had done the work I figured I'd throw it out for feedback.

Why:
- Enables developers to clone the repo and run `docker-compose up -d`
  able to start using the project
- New sample env format for environment variables
- New mechanisms for running tests by using `docker-compose run api npm test`

Thanks!

### CODE REVIEW

**Comment by zokier** [comment]
I find having a Dockerfile ready to go useful, but I'm not sure why @christopherhein decided to use CentOS, and an old version of that, as a base. I would think using official Node image would make more sense? I did that on [my version](https://github.com/zokier/pushd/blob/master/Dockerfile).

**Comment by christopherhein** [comment]
Nice work @zokier do you want me to close mine and you can submit yours? Looks like you're using the same `settings.coffee` as well so we're 1005 compliant with each other…

**Comment by zokier** [comment]
Maybe @rs could chime in on what he would prefer?

**Comment by rs** [comment]
standard node image sounds better.

**Comment by zokier** [comment]
Ok. I want to make couple of tweaks, but then I make new pull request

**Comment by christopherhein** [comment]
Just cleaning up PRs sounds like I can close this?

**Comment by rs** [comment]
Sure

**Pull request closed without merging**
